### ISSUE TITLE
미들웨어 처리에 대해서 불필요한 함수 랩핑으로 보여짐

### ISSUE THREAD

**Issue by suhanlee** [HHEntertainment/express-ts-server#1]
https://github.com/HHEntertainment/express-ts-server/blob/3cac2ecfdc60b0622600a5fdec7b7e279028b110/src/index.ts#L18

이 부분이 다시 일단 함수로 감싸서 따로 분리할 필요가 사실 없는 듯 해요.
코드량이 많지 않아서 한 파일에서 한번에 볼 수 있는 것이 더 가독성이 좋을 듯 합니다.(좀더 선언적)

**Comment by HHEntertainment** [comment]
이 부분은 사실 다른 미들 웨어들과 같은 형식으로 맞추기 위함도 있고, 말씀하신 것 처럼 실제 코드량은 별로 없지만 미들웨러를 "등록"하는 행위 자체는 별도 파일로 빼고 "로거 미들웨어를 적용한다"라는 것을 좀더 강조하는 것이 더 가독성이 좋다고 개인적으로 생각하여서 이렇게 하였습니다. 또, 템플릿이다 보니 추후 로거 미들웨어 코드가 좀 더 추가될 가능성도 있어서 일단은 파일을 분리 해 두었습니다.
