### ISSUE TITLE
Graphql type 과 resolvers 는 분리해서 처리하는 것이 좋을 듯 합니다.

### ISSUE THREAD

**Issue by suhanlee** [HHEntertainment/express-ts-server#12]
추후 확장성을 위해서 type 과 resolvers 는 분리해서 처리하는 것이 좋을 듯 합니다.

**Comment by HHEntertainment** [comment]
@suhanlee 어떤 점에서 type과 resolvers로 디렉토리를 구분하는 구조가 확장성에 더 유리할까요?
일단, 제가 구분한 방식은 currency안에 관련된 타입정의 파일과 query.resovler.ts, mutation.resolver.ts 이렇게 총 3개의 파일을 두었습니다. 최대한 모델별로 잘 구분하려는 것이 목적이기는 했는데, 어떤 점 때문에 확장성에서 trade/off가 있을까요?
