### ISSUE TITLE
에러 핸들링시에 어떻게 처리할지 코드 작성이 필요

### ISSUE THREAD

**Issue by suhanlee** [HHEntertainment/express-ts-server#3]
https://github.com/HHEntertainment/express-ts-server/blob/3cac2ecfdc60b0622600a5fdec7b7e279028b110/src/middlewares/error-handling.middleware.ts#L4

이것은 아직 작성 안한 듯 하지만 에러 핸들링시에 응답 값으로 어떻게 대응할지에 대한 코드를 넣는 부분에서 좀 더 고민이 필요할 듯 해요. 왜냐하면 HTTP STATUS 를 어떤 값으로 반환할지, 그리고 에러 데이터를 실제로 반환해보면서 좀 더 구체적인 논의가 가능하기 때문입니다.

또한 예외를 처리 하지 못한 에러는 추후에 코드 수정후 반영하기 위해서 크래시 리포트를 추가해줘야 합니다.

**Comment by HHEntertainment** [comment]
네, 로직 에러 이외에 기본적으로 추가되어야할 에러들(404, 401, 500 등)에 대한 템플릿에 대해서 추가적으로 고민해보겠습니다.
