### ISSUE TITLE
이 미들웨어의 이름은 왜 하이픈(-) 이 들어가 있나요?

### ISSUE THREAD

**Issue by suhanlee** [HHEntertainment/express-ts-server#4]
https://github.com/HHEntertainment/express-ts-server/blob/3cac2ecfdc60b0622600a5fdec7b7e279028b110/src/middlewares/error-handling.middleware.ts#L1

파일 이름이 전반적으로 Camel Case 를 따르는 것 같은데 이 파일은 그러지 않는 듯 합니다.

**Comment by HHEntertainment** [comment]
넹 ㅋㅋㅋ 수정하겠습니다.
