### ISSUE TITLE
HTTP spec 을 준수하면서 Authorization 을 구현해야 함

### ISSUE THREAD

**Issue by suhanlee** [HHEntertainment/express-ts-server#5]
https://github.com/HHEntertainment/express-ts-server/blob/3cac2ecfdc60b0622600a5fdec7b7e279028b110/src/graphql/withAuthCheck.ts#L10

일단 아래의 스펙 문서를 먼저 읽어주세요.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication

일단 첫번째로 authorization 이 아니라 Authorization 으로 처리 되어야 할 듯 합니다.
두번째로 값 자체가 <type> <credential> 순서이기 때문에 먼저 Bearer 를 구분해야 합니다.
세번째로 token 변수가 값이 유효하지 않거나 비어져 있으면 먼저 예외를 던져도 될 듯하네요.

**Comment by HHEntertainment** [comment]
아 넵. 일단 ` authorization` -> `Authorization` 수정하겠습니다. JWT 토큰 검증 관련해서는 아직 따로 더 개발하지 않은 상태입니다.

**Comment by HHEntertainment** [comment]
@suhanlee 확인을 해보니, Typescript에서 정의된 HTTP Header 타입들이 소문자로 정의되어있어 별도로 정의하지 않으면 위와 같은 형태로 할당해야합니다. 좀 합리적이지 않은것 같아서 찾아보니, HTTP 스펙상, HTTP 헤더들은 case-sensitive 하지 않다고 합니다.

https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2
