### ISSUE TITLE
불필요한 것으로 보여지는 상수

### ISSUE THREAD

**Issue by suhanlee** [HHEntertainment/express-ts-server#7]
https://github.com/HHEntertainment/express-ts-server/blob/3cac2ecfdc60b0622600a5fdec7b7e279028b110/src/env.ts#L9

일단 상수의 이름 자체가 abcd 소문자이고
불필요해 보이는 것으로 보여집니다.

**Comment by HHEntertainment** [comment]
이것은 그냥 템플릿으로 만든 Repo라 그냥 예시로 추가한 글로볼 상수입니다 ㅋㅋ

**Comment by HHEntertainment** [comment]
추가적으로, .env.sample 파일도 추가하도록 해야겠네요.

**Comment by HHEntertainment** [comment]
제거하고 sample도 추가하였습니다.
