### ISSUE TITLE
환경변수에 대해서 fallback 처리가 어디서도 되어 있지 않음

### ISSUE THREAD

**Issue by suhanlee** [HHEntertainment/express-ts-server#8]
https://github.com/HHEntertainment/express-ts-server/blob/3cac2ecfdc60b0622600a5fdec7b7e279028b110/src/index.ts#L12

```
process.env.NODE_ENV
process.env.PORT 
```

위의 환경 변수 등에 대해서 fallback 처리가 되어 있어서 기본 값 지정이나 (ex development 나 3000 등으로) 값이 없을 경우에 예외를 던지는 등의 에러 핸들링이 추가 되어야 할 듯 합니다.

**Comment by HHEntertainment** [comment]
감사합니다. 환경변수 fallback 처리도 추가하도록 하겠습니다.
