### ISSUE TITLE
로깅 처리가 일관성이 떨어지는 듯

### ISSUE THREAD

**Issue by suhanlee** [HHEntertainment/express-ts-server#9]
https://github.com/HHEntertainment/express-ts-server/blob/3cac2ecfdc60b0622600a5fdec7b7e279028b110/src/env.ts#L16

이 부분은 console.log 로 처리 되고 있는데
다른 곳은 별도의 미들웨어로 쓰고 있는 듯해서 확인이 필요하고
로깅 자체를 화면 출력으로 할지 아니면 별도로 파일을 써서 로깅 처리를 할지 등등을 고민이 필요합니다. (로그 어그리게이션이라고 치면 fluentd 등등이 나옵니다.)

https://github.com/HHEntertainment/express-ts-server/blob/3cac2ecfdc60b0622600a5fdec7b7e279028b110/src/middlewares/logger.middleware.ts#L5

환경별로 로그레벨을 출력 수준을 조절할 수 있고, Prefix 를 추가할 수도 있습니다.

**Comment by HHEntertainment** [comment]
로깅에 관련해서 많은 고민을 해보지는 못했습니다. 더 고민해보도록 하겠습니다.
